# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - fasm fnc.asm fnc.o
      - clang main.c fnc.o -o a.out
      - rm fnc.o # clean dupa ce lucram
